[mysql]
    [mysql.default]
        host = "127.0.0.1"
        port = 3306
        username = "root"
        password = "123456"
        max_conn = 20
        max_idle = 10

[redis]
    [redis.default]
        host = "127.0.0.1"
        port = 6379
        db = 1
        password = ""

[basic]
    log = "test-path"