[mysql]
    [mysql.default]
        host = "127.0.0.1"
        port = 3306
        db = "blog"
        username = "root"
        password = "123456"
        max_con = 1
        max_idle = 50
        timeout = 10

[redis]
    [redis.default]
        host = "127.0.0.1"
        port = 6379
        db = 2
        password = ""
        max_idle = 6
        max_active = 10
        idle_timeout = 60

[basic]
    log = "test-path"