[mysql]
    [mysql.default]
        host = ""
        port = 3306
        db = "task"
        username = ""
        password = ""
        max_con = 1
        max_idle = 50
        timeout = 10
    [mysql.permission]
        host = ""
        port = 3306
        db = "permission"
        username = ""
        password = ""
        max_con = 1
        max_idle = 50
        timeout = 10

[redis]
    [redis.default]
        host = "127.0.0.1"
        port = 6379
        db = 2
        password = ""
        max_idle = 6
        max_active = 10
        idle_timeout = 60

[log]
    [log.default]
        max_size = 100   # 文件大小为100M
        max_backups = 7  # 备份数量
        max_age = 30     # 最多保留多少天
        file = "/data0/logs/dawn-go/default.log"
    [log.access]
        max_size = 100   # 文件大小为100M
        max_backups = 7  # 备份数量
        max_age = 30     # 最多保留多少天
        file = "/data0/logs/dawn-go/access.log"

[basic]
    log = "test-path"
